version: "2"

services:


  icat:
    build: icat/.
    container_name: icat


  ies:
    build: ies/.
    container_name: ies
    links:
      - icat
    depends_on: 
      - icat
    tty: true
    entrypoint: /wait-for-it.sh icat:5432 
    command:  -- /crodstart.sh 


  irs:
    build: irs/.
    links:
      - ies
    depends_on:
      - ies
    tty: true
    entrypoint: /wait-for-it.sh ies:1247
    command: -- /cabstart.sh


  icom:
    build: icom/.
    container_name: icom
    hostname: SEABASS
    links:
      - ies
    depends_on:
      - ies
    tty: true
    volumes:
      - "${SEABASS_MOUNT_PATH}:/mnt/"
    entrypoint: /wait-for-it.sh ies:1247
    command: -- /comstart.sh
